apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: v1
data:
  APP_MESSAGE: Hi And Welcome To Course App!
  APP_REDIS_URL: redis://redis:6379/0
  APP_STORE: redis
kind: ConfigMap
metadata:
  name: web-config
  namespace: development
---
apiVersion: v1
kind: Service
metadata:
  name: course-app-svc
  namespace: development
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: course-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-app
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 40%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: course-app
    spec:
      containers:
      - env:
        - name: APP_MESSAGE
          valueFrom:
            configMapKeyRef:
              key: APP_MESSAGE
              name: web-config
        - name: APP_STORE
          valueFrom:
            configMapKeyRef:
              key: APP_STORE
              name: web-config
        - name: APP_REDIS_URL
          valueFrom:
            configMapKeyRef:
              key: APP_REDIS_URL
              name: web-config
        image: demo.goharbor.io/lesson06/course-app:v1.0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        name: course-app
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: development
spec:
  ingressClassName: traefik
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          service:
            name: course-app-svc
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - localhost
