apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: course-app-development
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/course-app/overlays/development
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      dragonfly_replicas: "1"
      app_replicas: "1"